[package]
name = "sensei"
version = "0.2.9"
authors = ["Eduardo Flores <edfloreshz@gmail.com>"]
edition = "2018"
license = "GPL-2.0"
description = "Sensei is a simple command line tool to open documentation for any crate."
homepage = "https://sensei.edfloreshz.dev/"
documentation = "https://docs.rs/sensei"
repository = "https://github.com/edfloreshz/sensei/"
readme = "README.md"
exclude = ["docs/*"]

[[bin]]
name = "sns"
path = "src/main.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2", features = ["derive"] }
open = "3"
